apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmlsite-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: ghcr.io/86alessio33/html-page:v1
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp-service
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapp
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: webapp
  name: webapp-page
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: webapp-service
  tls:
    termination: edge   
    insecureEdgeTerminationPolicy: Redirect
